name: my_grovia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/branding/mygrovia_logo.png
    - assets/illustration/empty_collection_plant.svg

flutter_launcher_icons:
  android: true
  image_path: "assets/branding/mygrovia_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/branding/mygrovia_logo.PNG"
  image_dark: "assets/branding/mygrovia_logo.PNG"
  android: true
  ios: false
  web: false

  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
    image: "assets/branding/mygrovia_logo.PNG"
    image_dark: "assets/branding/mygrovia_logo.PNG"